#include "install.h"
#include "utils.h"
#include "config.h"
#include <iostream>
#include <fstream>
#include <cstdlib>

namespace install {

const char* HOOK_CONTENT = R"HOOK(# SysPilot hook – autogenerated by syspilot install
# Source this in your ~/.bashrc to enable logging:
#   source ~/.syspilot/syspilot.sh

if [ -n "$SYSPILOT_HOOK_LOADED" ]; then
    return
fi
export SYSPILOT_HOOK_LOADED=1

__syspilot_preexec() {
    echo "$(date +%s) $(pwd) $1" >> ~/.syspilot/command_start.log
}

__syspilot_precmd() {
    local exit_code=$?
    local last_cmd=$(history 1 | sed 's/^ *[0-9]* *//')
    echo "$(date -Iseconds) | $(pwd) | ${last_cmd} | ${exit_code}" >> ~/.syspilot/context.log
}

PROMPT_COMMAND="__syspilot_precmd; $PROMPT_COMMAND"
trap '__syspilot_preexec "$BASH_COMMAND"' DEBUG
)HOOK";

bool install() {
    std::string dir = utils::get_syspilot_directory();
    utils::create_directory_recursive(dir);
    
    // Create log files if they don't exist
    const std::vector<std::string> files = {"session.log", "context.log", "command_start.log"};
    for (const auto& f : files) {
        std::string path = dir + "/" + f;
        if (!utils::file_exists(path)) {
            std::ofstream file(path);
            file.close();
        }
    }
    
    // Create default config if it doesn't exist
    std::string config_path = dir + "/config.json";
    if (!utils::file_exists(config_path)) {
        Config default_conf;
        config::save(default_conf);
    }
    
    // Write hook script
    std::string hook_path = dir + "/syspilot.sh";
    bool write_ok = utils::write_file_content(hook_path, HOOK_CONTENT);
    if (!write_ok) {
        std::cerr << "❌ Failed to write hook script to " << hook_path << std::endl;
        return false;
    }
    
    std::cout << "✅ SysPilot installed successfully." << std::endl;
    std::cout << "Hook script created at: " << hook_path << std::endl;
    std::cout << "\nTo enable SysPilot, add this line to your ~/.bashrc:" << std::endl;
    std::cout << "  source " << hook_path << std::endl;
    std::cout << "\nThen restart your terminal or run: source ~/.bashrc" << std::endl;
    return true;
}

bool uninstall() {
    std::string dir = utils::get_syspilot_directory();
    std::string hook_path = dir + "/syspilot.sh";
    if (utils::file_exists(hook_path)) {
        utils::delete_file(hook_path);
        std::cout << "Removed hook script: " << hook_path << std::endl;
    }
    std::cout << "To completely remove SysPilot, delete the directory: " << dir << std::endl;
    std::cout << "Also remember to remove the 'source' line from your ~/.bashrc." << std::endl;
    return true;
}

bool status() {
    std::string dir = utils::get_syspilot_directory();
    std::string hook_path = dir + "/syspilot.sh";
    if (utils::file_exists(hook_path)) {
        std::cout << "✅ Hook script found: " << hook_path << std::endl;
        const char* hook_loaded = std::getenv("SYSPILOT_HOOK_LOADED");
        if (hook_loaded) {
            std::cout << "✅ Hook is active in this shell." << std::endl;
        } else {
            std::cout << "⚠️  Hook is not active in the current shell environment." << std::endl;
            std::cout << "Did you run `source ~/.syspilot/syspilot.sh` or add it to ~/.bashrc?" << std::endl;
        }
    } else {
        std::cout << "❌ SysPilot is not installed. Run `syspilot install` first." << std::endl;
    }
    return true;
}

} // namespace install
